version: '3'

services:
  db:
    container_name: postgresdb-{{cookiecutter.repo_name}}
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: {{cookiecutter.repo_name}}
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - project.env
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres-data: