version: '3'

services:
  db:
    container_name: postgresdb-{{cookiecutter.repo_name}}
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: {{cookiecutter.repo_name}}
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - project.env
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      
volumes:
  postgres-data:
